import { useEffect, useState } from 'react'
import { WithId } from 'mongodb'
import { NextPage } from 'next'
import Link from 'next/link'

import { deleteDepartment, Department, listDepartments } from '../../lib/pK'

import styles from '../../styles/Home.module.css'
import DepartmentList, { DepartmentRow } from '../../lib/DepartmentList'
import Head from 'next/head'

type Props = {
}

const Departments: NextPage<Props> = () => {
    const [rows, setRows] = useState<DepartmentRow[] | null>(null)

    useEffect(() => {
        let isMounted = true

        let refreshList = () => {
            listDepartments().then((departmentsList) => {
                if (!isMounted)
                    return

                const onDeleteClick = (department: WithId<Department>) => {
                    setRows(null)
                    deleteDepartment(department._id)
                        .finally(refreshList)
                }

                setRows(departmentsList.map((department): DepartmentRow => ({
                    id: department._id,
                    name: department.name,
                    links: <>
                        <Link href={`/departments/${department._id}`}><a>Edit</a></Link>
                        <Link href=''><a onClick={() => onDeleteClick(department)}>Delete</a></Link>
                    </>,
                })))
            })
        }

        refreshList()

        return () => {
            isMounted = false
            refreshList = () => undefined
        }
    }, [])

    return <div className={styles.container}>
        <Head>
            <title>pK | Departments</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <h1>Departments</h1>
        <DepartmentList departments={rows} />
        <br />
        <Link href={'/departments/new'}><a>New</a></Link>
    </div>
}

export default Departments
